# Generated by Django 3.1.2 on 2020-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fundus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundus_Img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=120)),
                ('path', models.TextField()),
            ],
        ),
    ]
