# Generated by Django 3.1.3 on 2020-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundus', '0003_fundus_fundus_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundus',
            name='analysis',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
